version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["nodejs"]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/harikrishnanum/DataForge"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"