version: '3'
services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniostorage
    volumes:
      - ~/minio/data:/data
    ports:
      - 9000:9000
      - 9090:9090
    restart: always
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      xpack.security.enabled: "false"
    ports:
      - 9200:9200
    restart: always
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.2
    ports:
      - 5601:5601
    restart: always
    networks:
      - elastic

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

networks:
  elastic:
